# Golang CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-go/ for more details
version: 2

jobs:
  "dep":
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/hypnoglow/gormzap
    steps:
      - checkout
      - run: curl -sSL https://github.com/golang/dep/releases/download/v0.4.1/dep-linux-amd64 -o /go/bin/dep
      - run: chmod +x /go/bin/dep
      - run: /go/bin/dep init -v
      - persist_to_workspace:
          root: /go/src/github.com/hypnoglow
          paths:
            - gormzap
  "test":
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/hypnoglow/gormzap
    steps:
      - attach_workspace:
          at: /go/src/github.com/hypnoglow
      - run: go test -v ./...
workflows:
  version: 2
  common-pipeline:
    jobs:
      - dep
      - test:
          requires:
            - dep
